#cloud-config
# If this is set, 'root' will not be able to ssh in and they
# will get a message to login instead as the default $user
disable_root: true

# This will cause the set+update hostname module to not operate (if true)
preserve_hostname: false

# The modules that run in the 'init' stage
cloud_init_modules:
  - migrator
  - seed_random
  - bootcmd
  - write_files
  - growpart
  - resizefs
  - disk_setup
  - mounts
  - set_hostname
  - update_hostname
  - update_etc_hosts
  - ca_certs
  - rsyslog
  - users_groups
  - ssh

# The modules that run in the 'config' stage
cloud_config_modules:
  - ubuntu_autoinstall
  - ssh_import_id
  - locale
  - set_passwords
  - grub_dpkg
  - apt_pipelining
  - apt_configure
  - ntp
  - timezone "Africa/Lagos"
  - runcmd

# The modules that run in the 'final' stage
cloud_final_modules:
  - package_update_upgrade_install
  - ubuntu_drivers
  - write_files_deferred
  - scripts_vendor
  - scripts_per_once
  - scripts_per_boot
  - scripts_per_instance
  - scripts_user
  - ssh_authkey_fingerprints
  - keys_to_console
  - power_state_change

package_update: true
package_upgrade: true

packages:
  - postgresql-client
  - openjdk-17-jre-headless

hostname: login
fqdn: login.xplora.local
prefer_fqdn_over_hostname: true
# manage_etc_hosts: true
create_hostname_file: true

runcmd:
  - [ cd, /opt ]
  - [ wget, https://github.com/keycloak/keycloak/releases/download/24.0.2/keycloak-24.0.2.tar.gz ]
  - [ tar, xf, keycloak-24.0.2.tar.gz ]
  - [ export, KEYCLOAK_ADMIN=admin  ] 
  - [ export, KEYCLOAK_ADMIN_PASSWORD=password ] 
  - [ cd, keycloak-24.0.2 ]
  -  echo "$(hostname -I | awk '{print "login.xplora.local login ", $1}')" >> /etc/hosts.conf 
  -  echo "db=postgres" >> conf/keycloak.conf 
  -  echo 'db-username=keycloak' >> conf/keycloak.conf 
  -  echo "db-password=password" >> conf/keycloak.conf 
  -  echo 'db-url-host=10.35.51.70' >> conf/keycloak.conf 
  -  echo 'db-url-database=keycloakdb' >> conf/keycloak.conf 
  -  echo 'db-url-port=5432' >> conf/keycloak.conf 
  # -  echo "db-url=jdbc:postgresql://10.35.51.127/keycloakdb" >> conf/keycloak.conf 
  -  echo "hostname=login.xplora.local" >> conf/keycloak.conf 
  -  echo "hostname-strict=false" >> conf/keycloak.conf 
  - [ bin/kc.sh, build ]
  - [ bin/kc.sh, start-dev ]

